config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Production authentication routes
  get 'login', to: 'sessions#new', as: :login
  delete 'logout', to: 'sessions#destroy', as: :logout

  # Development and testing authentication routes
  if Rails.env.development? || Rails.env.test?
    get 'dev_login', to: 'dev_sessions#new', as: :dev_login
    post 'dev_login', to: 'dev_sessions#create'
    delete 'dev_logout', to: 'dev_sessions#destroy', as: :dev_logout
    get 'shibboleth_login', to: 'test_shibboleth#login'
    get '/test_user_auth', to: 'test_user_authentication#index'
    get '/admin_area', to: 'test_user_authentication#admin_area'
  end

  # Admin Namespace for Managing Users
  namespace :admin do
    resources :users # Admins can manage users (CRUD)
  end

  # User Management (Outside Admin, Excluding Create)
  resources :users, only: %i[edit update show]

  # Conservation Records and Nested Resources
  resources :conservation_records do
    resources :in_house_repair_records
    resources :external_repair_records
    resources :con_tech_records
    resources :treatment_reports
    resources :abbreviated_treatment_reports
    resources :cost_return_reports

    # Conservation Records-Specific Actions
    member do
      get 'conservation_worksheet'
      get 'treatment_report'
      get 'abbreviated_treatment_report'
    end
  end

  # Miscellaneous Resource Routes
  resources :staff_codes, except: [:destroy]
  resources :controlled_vocabularies, except: [:destroy]
  resources :activity
  resources :reports do
    get 'download_csv', on: :collection
  end

  # Search Routes
  get 'search/help', to: 'search#help', as: :search_help
  get 'search', to: 'search#results', as: :search

  # Root and Front Routes
  root 'front#index'
  get 'front/index', to: 'front#index'
end

app/models/treatment_report.rb
# frozen_string_literal: true

class TreatmentReport < ApplicationRecord
  belongs_to :conservation_record

  has_paper_trail on: %i[update destroy]

  has_rich_text :abbreviated_treatment_report
end

app/controllers/treatment_reports_controller.rb
# frozen_string_literal: true

class TreatmentReportsController < ApplicationController
  def create
    @treatment_report = TreatmentReport.new(treatment_report_params)
    @treatment_report.conservation_record_id = params[:conservation_record_id]
    @treatment_report.save

    flash
    redirect_to "#{conservation_record_path(@treatment_report.conservation_record)}#treatment-report-tab", notice: 'Treatment record saved successfully!'
  end

  def update
    @treatment_report = TreatmentReport.find(params[:id])

    @treatment_report.update(treatment_report_params)
    redirect_to "#{conservation_record_path(@treatment_report.conservation_record)}#treatment-report-tab",
                notice: 'Treatment Record updated successfully!'
  end

  private

  def treatment_report_params
    params.require(:treatment_report).permit(:description_general_remarks,
                                             :description_binding,
                                             :description_textblock,
                                             :description_primary_support,
                                             :description_medium,
                                             :description_attachments_inserts,
                                             :description_housing,
                                             :condition_summary,
                                             :condition_binding,
                                             :condition_textblock,
                                             :condition_primary_support,
                                             :condition_medium,
                                             :condition_housing_id,
                                             :condition_housing_narrative,
                                             :condition_attachments_inserts,
                                             :condition_previous_treatment,
                                             :condition_materials_analysis,
                                             :treatment_proposal_proposal,
                                             :treatment_proposal_housing_need_id,
                                             :treatment_proposal_factors_influencing_treatment,
                                             :treatment_proposal_performed_treatment,
                                             :treatment_proposal_housing_provided_id,
                                             :treatment_proposal_housing_narrative,
                                             :treatment_proposal_storage_and_handling_notes,
                                             :treatment_proposal_total_treatment_time,
                                             :abbreviated_treatment_report)
  end
end

app/views/treatment_reports/_abbreviated_treatment_report_form.html.erb
<br>
<div class="header">
  <h3>Abbreviated Treatment Report</h3>
</div>

  <%= form_with(model: [@conservation_record, @conservation_record.treatment_report], class: 'disable_input') do |f| %>
    <div class="form-group">
      <p>
        <%= f.text_area :abbreviated_treatment_report, class: 'form-control' %>
      </p>
      <p>
        <%= f.submit 'Save Abbreviated Treatment Report', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/treatment_reports/_form.html.erb
<br>
<div class="header">
  <h3>Treatment Report</h3>
  <%= link_to 'Download Treatment Report', treatment_report_conservation_record_path(@conservation_record), target: '_blank' %>
</div>
<br>
<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="description-tab" data-bs-toggle="tab" href="#description" role="tab" aria-controls="description" aria-selected="true">Description</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="condition-tab" data-bs-toggle="tab" href="#condition" role="tab" aria-controls="condition" aria-selected="false">Condition</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="treatment-proposal-tab" data-bs-toggle="tab" href="#treatment-proposal" role="tab" aria-controls="treatment-proposal" aria-selected="false">Treatment Proposal</a>
  </li>
</ul>

<%= form_with(model: [@conservation_record, @conservation_record.treatment_report], class: 'disable_input') do |f| %>
<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active" id="description" role="tabpanel" aria-labelledby="description-tab">
    <div class="form-group">
      <p>
        <%= f.label :description_general_remarks, "General Remarks" %>
        <%= f.text_area :description_general_remarks, class: 'form-control' %>
      </p>

      <p>
        <%= f.label :description_binding, "Binding" %>
        <%= f.text_area :description_binding, class: 'form-control' %>
      </p>

      <p>
        <%= f.label :description_textblock, "Text Block" %>
        <%= f.text_area :description_textblock, class: 'form-control' %>
      </p>

      <p>
        <%= f.label :description_primary_support, "Primary Support" %>
        <%= f.text_area :description_primary_support, class: 'form-control' %>
      </p>

      <p>
        <%= f.label :description_medium, "Medium" %>
        <%= f.text_area :description_medium, class: 'form-control' %>
      </p>

      <p>
        <%= f.label :description_attachments_inserts, "Attachments | Inserts" %>
        <%= f.text_area :description_attachments_inserts, class: 'form-control' %>
      </p>

      <p>
        <%= f.label :description_housing, "Housing" %>
        <%= f.text_area :description_housing, class: 'form-control' %>
      </p>
    </div>
  </div>
  <div class="tab-pane fade" id="condition" role="tabpanel" aria-labelledby="condition-tab">
    <p>
      <%= f.label :condition_summary, "Summary" %>
      <%= f.text_area :condition_summary, class: 'form-control' %>
    </p>

    <p>
      <%= f.label :condition_binding, "Binding" %>
      <%= f.text_area :condition_binding, class: 'form-control' %>
    </p>

    <p>
      <%= f.label :condition_textblock, "Text Block" %>
      <%= f.text_area :condition_textblock, class: 'form-control' %>
    </p>

    <p>
      <%= f.label :condition_primary_support, "Primary Support" %>
      <%= f.text_area :condition_primary_support, class: 'form-control' %>
    </p>

    <p>
      <%= f.label :condition_medium, "Medium" %>
      <%= f.text_area :condition_medium, class: 'form-control' %>
    </p>

    <p>
      <%= f.label :condition_housing_id, "Housing" %>
      <%= f.select(:condition_housing_id, options_from_collection_for_select(@housing, "id", "key", @conservation_record.treatment_report.condition_housing_id), { prompt: 'Select Housing' }, { :class => 'form-control' }) %>
    </p>

    <p>
      <%= f.label :condition_housing_narrative, "Housing Narrative" %>
      <%= f.text_area :condition_housing_narrative, class: 'form-control' %>
    </p>

    <p>
      <%= f.label :condition_attachments_inserts, "Attachments | Inserts" %>
      <%= f.text_area :condition_attachments_inserts, class: 'form-control' %>
    </p>

    <p>
      <%= f.label :condition_previous_treatment, "Previous Treatment" %>
      <%= f.text_area :condition_previous_treatment, class: 'form-control' %>
    </p>

    <p>
      <%= f.label :condition_materials_analysis, "Materials Analysis" %>
      <%= f.text_area :condition_materials_analysis, class: 'form-control' %>
    </p>
  </div>
  <div class="tab-pane fade" id="treatment-proposal" role="tabpanel" aria-labelledby="treatment-proposal-tab">
    <p>
      <%= f.label :treatment_proposal_proposal, "Proposal" %>
      <%= f.text_area :treatment_proposal_proposal, class: 'form-control' %>
    </p>

    <p>
      <%= f.label :treatment_proposal_housing_need_id, "Housing Need" %>
      <%= f.select(:treatment_proposal_housing_need_id, options_from_collection_for_select(@housing, "id", "key", @conservation_record.treatment_report.treatment_proposal_housing_need_id), { prompt: 'Select Housing' }, { :class => 'form-control' }) %>
    </p>

    <p>
      <%= f.label :treatment_proposal_factors_influencing_treatment, "Factors Influencing Treatment" %>
      <%= f.text_area :treatment_proposal_factors_influencing_treatment, class: 'form-control' %>
    </p>

    <p>
      <%= f.label :treatment_proposal_performed_treatment, "Performed Treatment" %>
      <%= f.text_area :treatment_proposal_performed_treatment, class: 'form-control' %>
    </p>

    <p>
      <%= f.label :treatment_proposal_housing_provided_id, "Housing Provided" %>
      <%= f.select(:treatment_proposal_housing_provided_id, options_from_collection_for_select(@housing, "id", "key", @conservation_record.treatment_report.treatment_proposal_housing_provided_id), { prompt: 'Select Housing' }, { :class => 'form-control' }) %>
    </p>

    <p>
      <%= f.label :treatment_proposal_housing_narrative, "Housing Narrative" %>
      <%= f.text_area :treatment_proposal_housing_narrative, class: 'form-control' %>
    </p>

    <p>
      <%= f.label :treatment_proposal_storage_and_handling_notes, "Storage and Handling Notes" %>
      <%= f.text_area :treatment_proposal_storage_and_handling_notes, class: 'form-control' %>
    </p>

    <p>
      <%= f.label :treatment_proposal_total_treatment_time, "Total Treatment Time" %>
      <%= f.text_area :treatment_proposal_total_treatment_time, class: 'form-control' %>
    </p>
  </div>
</div>


<p>
  <%= f.submit 'Save Treatment Report', class: 'btn btn-primary' %>
</p>

<% end %>
<br />