config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Production authentication routes
  get 'login', to: 'sessions#new', as: :login
  delete 'logout', to: 'sessions#destroy', as: :logout

  # Development and testing authentication routes
  if Rails.env.development? || Rails.env.test?
    get 'dev_login', to: 'dev_sessions#new', as: :dev_login
    post 'dev_login', to: 'dev_sessions#create'
    delete 'dev_logout', to: 'dev_sessions#destroy', as: :dev_logout
    get 'shibboleth_login', to: 'test_shibboleth#login'
    get '/test_user_auth', to: 'test_user_authentication#index'
    get '/admin_area', to: 'test_user_authentication#admin_area'
  end

  # Admin Namespace for Managing Users
  namespace :admin do
    resources :users # Admins can manage users (CRUD)
  end

  # User Management (Outside Admin, Excluding Create)
  resources :users, only: %i[edit update show]

  # Conservation Records and Nested Resources
  resources :conservation_records do
    resources :in_house_repair_records
    resources :external_repair_records
    resources :con_tech_records
    resources :treatment_reports
    resources :abbreviated_treatment_reports
    resources :cost_return_reports

    # Conservation Records-Specific Actions
    member do
      get 'conservation_worksheet'
      get 'treatment_report'
      get 'abbreviated_treatment_report'
    end
  end

  # Miscellaneous Resource Routes
  resources :staff_codes, except: [:destroy]
  resources :controlled_vocabularies, except: [:destroy]
  resources :activity
  resources :reports do
    get 'download_csv', on: :collection
  end

  # Search Routes
  get 'search/help', to: 'search#help', as: :search_help
  get 'search', to: 'search#results', as: :search

  # Root and Front Routes
  root 'front#index'
  get 'front/index', to: 'front#index'
end

app/models/controlled_vocabulary.rb
# frozen_string_literal: true

class ControlledVocabulary < ApplicationRecord
  validates :vocabulary, :key, presence: true
end

app/controllers/controlled_vocabularies_controller.rb
# frozen_string_literal: true

class ControlledVocabulariesController < ApplicationController
  before_action :set_controlled_vocabulary, only: %i[show edit update]
  load_and_authorize_resource

  # GET /controlled_vocabularies
  # GET /controlled_vocabularies.json
  def index
    @controlled_vocabularies = ControlledVocabulary.all
  end

  # GET /controlled_vocabularies/1
  # GET /controlled_vocabularies/1.json
  def show; end

  # GET /controlled_vocabularies/new
  def new
    @controlled_vocabulary = ControlledVocabulary.new
  end

  # GET /controlled_vocabularies/1/edit
  def edit; end

  # POST /controlled_vocabularies
  # POST /controlled_vocabularies.json
  def create
    @controlled_vocabulary = ControlledVocabulary.new(controlled_vocabulary_params)

    respond_to do |format|
      if @controlled_vocabulary.save
        format.html { redirect_to @controlled_vocabulary, notice: 'Controlled vocabulary was successfully created.' }
        format.json { render :show, status: :created, location: @controlled_vocabulary }
      else
        format.html { render :new }
        format.json { render json: @controlled_vocabulary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /controlled_vocabularies/1
  # PATCH/PUT /controlled_vocabularies/1.json
  def update
    respond_to do |format|
      if @controlled_vocabulary.update(controlled_vocabulary_params)
        format.html { redirect_to @controlled_vocabulary, notice: 'Controlled vocabulary was successfully updated.' }
        format.json { render :show, status: :ok, location: @controlled_vocabulary }
      else
        format.html { render :edit }
        format.json { render json: @controlled_vocabulary.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_controlled_vocabulary
    @controlled_vocabulary = ControlledVocabulary.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def controlled_vocabulary_params
    params.require(:controlled_vocabulary).permit(:vocabulary, :key, :active, :favorite)
  end
end

app/views/controlled_vocabularies/_form.html.erb
<%= form_with(model: controlled_vocabulary, local: true) do |form| %>
  <% if controlled_vocabulary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(controlled_vocabulary.errors.count, "error") %> prohibited this controlled_vocabulary from being saved:</h2>

      <ul>
      <% controlled_vocabulary.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-block">
  <div class="mb-3">
    <%= form.label :vocabulary %>
    <%= form.select(:vocabulary, ControlledVocabulary.pluck(:vocabulary).uniq, { include_blank: 'Select Vocabulary' }, {class: 'form-control'}) %>
 </div>

  <div class="mb-3">
    <%= form.label :key %>
    <%= form.text_field :key, class: 'form-control'%>
  </div>

  <div class="mb-3">
    <%= form.label :active %>
    <%= form.check_box :active,class: 'btn btn-primary' %>
  </div>

  <div class="mb-3">
    <%= form.label :favorite %>
    <%= form.check_box :favorite,class: 'btn btn-primary' %>
  </div>


  <div class="actions">
    <%= form.submit class: 'btn btn-primary'%>
  </div>
 <% end %>
 </div>

app/views/controlled_vocabularies/edit.html.erb
<h1>Editing Controlled Vocabulary</h1>

</br><%= render 'form', controlled_vocabulary: @controlled_vocabulary %>

</br><%= link_to 'Cancel', controlled_vocabularies_path, class: "btn btn-primary" %>

app/views/controlled_vocabularies/index.html.erb
<p id="notice"><%= notice %></p>

<div class="header">
  <h1>Controlled Vocabularies</h1>
  <% if can? :create, ControlledVocabulary %>
    <%= link_to 'New Controlled Vocabulary', new_controlled_vocabulary_path , class: "btn btn-primary justify-content-right"%>
  <% end %>
</div>


<table class="table">
  <thead>
    <tr>
      <th>Vocabulary</th>
      <th>Key</th>
      <th>Active</th>
      <th>Favorite</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @controlled_vocabularies.each do |controlled_vocabulary| %>
      <tr>
        <td><%= controlled_vocabulary.vocabulary %></td>
        <td><%= link_to controlled_vocabulary.key, controlled_vocabulary %></td>
        <td><%= controlled_vocabulary.active %></td>
        <td><%= controlled_vocabulary.favorite %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/controlled_vocabularies/new.html.erb
<h1>New Controlled Vocabulary</h1>
<br>
<%= render 'form', controlled_vocabulary: @controlled_vocabulary %>
<br>
<%= link_to 'Back', controlled_vocabularies_path %>

app/views/controlled_vocabularies/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <strong>Vocabulary:</strong>
  <strong> <%= @controlled_vocabulary.vocabulary %> </strong>
</h1>

<p>
  <strong>Key:</strong>
  <%= @controlled_vocabulary.key %>
</p>

<p>
  <strong>Active:</strong>
  <%= @controlled_vocabulary.active %>
</p>

<p>
  <strong>Favorite:</strong>
  <%= @controlled_vocabulary.favorite %>
</p>

<%= link_to 'Edit', edit_controlled_vocabulary_path(@controlled_vocabulary) %> |
<%= link_to 'Return to List', controlled_vocabularies_path %>