config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Production authentication routes
  get 'login', to: 'sessions#new', as: :login
  delete 'logout', to: 'sessions#destroy', as: :logout

  # Development and testing authentication routes
  if Rails.env.development? || Rails.env.test?
    get 'dev_login', to: 'dev_sessions#new', as: :dev_login
    post 'dev_login', to: 'dev_sessions#create'
    delete 'dev_logout', to: 'dev_sessions#destroy', as: :dev_logout
    get 'shibboleth_login', to: 'test_shibboleth#login'
    get '/test_user_auth', to: 'test_user_authentication#index'
    get '/admin_area', to: 'test_user_authentication#admin_area'
  end

  # Admin Namespace for Managing Users
  namespace :admin do
    resources :users # Admins can manage users (CRUD)
  end

  # User Management (Outside Admin, Excluding Create)
  resources :users, only: %i[edit update show]

  # Conservation Records and Nested Resources
  resources :conservation_records do
    resources :in_house_repair_records
    resources :external_repair_records
    resources :con_tech_records
    resources :treatment_reports
    resources :abbreviated_treatment_reports
    resources :cost_return_reports

    # Conservation Records-Specific Actions
    member do
      get 'conservation_worksheet'
      get 'treatment_report'
      get 'abbreviated_treatment_report'
    end
  end

  # Miscellaneous Resource Routes
  resources :staff_codes, except: [:destroy]
  resources :controlled_vocabularies, except: [:destroy]
  resources :activity
  resources :reports do
    get 'download_csv', on: :collection
  end

  # Search Routes
  get 'search/help', to: 'search#help', as: :search_help
  get 'search', to: 'search#results', as: :search

  # Root and Front Routes
  root 'front#index'
  get 'front/index', to: 'front#index'
end

app/helpers/navigation_helper.rb
# frozen_string_literal: true

module NavigationHelper
  AVAILABLE_LINKS = [
    { title: 'Conservation Records', path: :conservation_records_path, permission: [:read, ConservationRecord] },
    { title: 'Vocabularies', path: :controlled_vocabularies_path, permission: [:read, ControlledVocabulary] },
    { title: 'Users', path: :admin_users_path, permission: [:manage, User] },
    { title: 'Activity', path: :activity_index_path, permission: [:read, PaperTrail::Version] },
    { title: 'Reports', path: :reports_path, permission: [:manage, Report] },
    { title: 'Staff Codes', path: :staff_codes_path, permission: [:read, StaffCode] }
  ].freeze

  def navigation_links(user)
    return 'navigation/logged_out_navigation' if user.blank?

    'navigation/logged_in_navigation'
  end

  def nav_links_for_user
    AVAILABLE_LINKS.each_with_object([]) do |link, links|
      links << { title: link[:title], path: send(link[:path]) } if can?(*link[:permission])
    end
  end
end

app/views/navigation/_logged_in_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'Treatment Database', root_path, class: 'navbar-brand' %>

    <!-- Hamburger menu button -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Collapsible content -->
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ms-auto d-flex align-items-lg-center text-start text-lg-end">

        <% # Get navigation links for the current user %>
        <% nav_links_for_user.each_with_index do |link, index| %>
          <li class="nav-item d-flex justify-content-center align-items-center">
            <%= link_to(link[:title], link[:path], class: 'nav-link text-center') %>
          </li>
          <% if index < nav_links_for_user.size - 1 %>
            <li class="nav-item nav-link justify-content-center align-items-center divider">|</li>
          <% end %>
        <% end %>

        <!-- Search form -->
        <li class="nav-item d-flex justify-content-center align-items-center m-2">
          <form class="form-inline d-flex" action="<%= search_path %>" accept-charset="UTF-8" method="get">
            <input id="search" placeholder="Search" class="form-control me-2" type="text" name="search">
            <%= link_to "(?)", search_help_path, class: "search-help-icon align-self-center me-2" %>
            <button type="submit" class="btn btn-primary m-2">Search</button>
          </form>
        </li>

        <!-- User Dropdown -->
        <% if current_user.present? %>
          <li class="nav-item dropdown d-flex justify-content-center align-items-center m-2">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= current_user.display_name %>
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <%= link_to "Edit Account", edit_user_path(current_user), class: 'dropdown-item' %>
              <% if Rails.env.development? || Rails.env.test? %>
                <%= link_to 'Dev Sign Out', dev_logout_path, method: :delete, class: 'dropdown-item' %>
              <% end %>
              <%= link_to 'Sign Out', '#', class: 'dropdown-item', id: 'logout-button', data: { logout_url: logout_path } %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/navigation/_logged_out_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <div class="d-flex align-items-center w-100">
      <div class="me-auto">
        <%= link_to 'Treatment Database', root_path, class: 'navbar-brand' %>
      </div>
      <div>
        <% if Rails.env.development? || Rails.env.test? %>
          <%= button_to 'Dev Sign In', dev_login_path, method: :get, class: 'btn btn-secondary me-2' %>
        <% end %>
      </div>
      <div>
        <%= button_to 'Sign In', login_path, target: conservation_records_path, method: :get, class: 'btn btn-secondary' %>
      </div>
    </div>
  </div>
</nav>