config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Production authentication routes
  get 'login', to: 'sessions#new', as: :login
  delete 'logout', to: 'sessions#destroy', as: :logout

  # Development and testing authentication routes
  if Rails.env.development? || Rails.env.test?
    get 'dev_login', to: 'dev_sessions#new', as: :dev_login
    post 'dev_login', to: 'dev_sessions#create'
    delete 'dev_logout', to: 'dev_sessions#destroy', as: :dev_logout
    get 'shibboleth_login', to: 'test_shibboleth#login'
    get '/test_user_auth', to: 'test_user_authentication#index'
    get '/admin_area', to: 'test_user_authentication#admin_area'
  end

  # Admin Namespace for Managing Users
  namespace :admin do
    resources :users # Admins can manage users (CRUD)
  end

  # User Management (Outside Admin, Excluding Create)
  resources :users, only: %i[edit update show]

  # Conservation Records and Nested Resources
  resources :conservation_records do
    resources :in_house_repair_records
    resources :external_repair_records
    resources :con_tech_records
    resources :treatment_reports
    resources :abbreviated_treatment_reports
    resources :cost_return_reports

    # Conservation Records-Specific Actions
    member do
      get 'conservation_worksheet'
      get 'treatment_report'
      get 'abbreviated_treatment_report'
    end
  end

  # Miscellaneous Resource Routes
  resources :staff_codes, except: [:destroy]
  resources :controlled_vocabularies, except: [:destroy]
  resources :activity
  resources :reports do
    get 'download_csv', on: :collection
  end

  # Search Routes
  get 'search/help', to: 'search#help', as: :search_help
  get 'search', to: 'search#results', as: :search

  # Root and Front Routes
  root 'front#index'
  get 'front/index', to: 'front#index'
end

app/models/report.rb
# frozen_string_literal: true

class Report < ApplicationRecord
  has_one_attached :csv_file
end

app/controllers/reports_controller.rb
# frozen_string_literal: true

class ReportsController < ApplicationController
  load_and_authorize_resource

  def index
    @reports = Report.all
  end

  def create
    DataExportJob.perform_now
    flash[:notice] = "#{Report.last.csv_file.filename} is ready below."
    redirect_to reports_path
  end

  def destroy
    @report.csv_file.purge
    @report.destroy
    redirect_to reports_path
  end
end

app/helpers/reports_helper.rb
# frozen_string_literal: true

module ReportsHelper
end

app/views/reports/create.html.erb
<% if @results.empty? %> 
   <p> No Results </p> 
<% end %>
<div>
   <table width="100%">
      <col span="1" style="width: 25;">
      <col span="1" style="width: 25;">
      <col span="1" style="width: 25;">
      <col span="1" style="width: 25;">
      <tr>
        <th><b>Database ID</b></th>
        <th><b>Department</b></th>
        <th><b>title</b></th>
        <th><b>Item Record#</b></th>
      </tr>
      <% @results.each do |result| %>
      <tr>
        <td><%= result.conservation_record.id %></td>
        <td><%= controlled_vocabulary_lookup(result.conservation_record.department) %></td>
        <td><%= result.conservation_record.title %></td>
        <td><%= result.conservation_record.item_record_number %></td>
      </tr>
    </table>
</div>
<%end%>

app/views/reports/index.html.erb
<h1><%= 'Reports' %></h1>

<p>

<%= link_to 'New Report', reports_path, class: "btn btn-primary justify-content-right", method: :post %>
<p>Report may take a moment to complete.</p>

</p>
<table class="table">
  <thead>
    <tr>
      <th>Date Created</th>
      <th>File</th>
      <th colspan="4"></th>
    </tr>
  </thead>
<tbody>
<% unless @reports.nil? %>
  <% @reports.each do |report| %>
  <tr>
  <td>
    <%=report.created_at %>
  </td>
  <td>
    <%= link_to report.csv_file.filename, url_for(report.csv_file)  %>
  </td>
  <td>
    <%= button_to 'Delete', report_path(report), class: 'btn btn-danger', method: :delete, data: {confirm: 'Are you sure?'}  %>
  </td>

  </tr>
  <% end %>
<%end %>
</tbody>
</table>

app/views/reports/new.html.erb
<h3>Completed In House Repairs</h3>
</br>
<%= form_tag(reports_path, method: :get) do %>
   <%= label_tag(:search, "Start Date") %>
   <%= date_field_tag :start_date, params[:start_date] %> </br></br>
   <%= label_tag(:search, "End Date") %>
   <%= date_field_tag :end_date, params[:end_date] %> </br></br>
   <%= submit_tag("Search") %>
<% end %>
<br>
<br>
<h3> Completed without In-House Repairs </h3>
</br>
<%= form_tag(reports_path, method: :post) do %>
   <%= label_tag(:search, "Start Date") %>
   <%= date_field_tag :start_date, params[:start_date] %> </br></br>
   <%= label_tag(:search, "End Date") %>
   <%= date_field_tag :end_date, params[:end_date] %> </br></br>
   <%= submit_tag("Search") %>
<% end %>